// Generated by CoffeeScript 1.6.1
(function() {
  var Object;

  Object = (function() {

    function Object() {}

    Object.prototype.inititalize = function() {};

    return Object;

  })();

}).call(this);
